daemon on;
worker_processes 1;
pid /tmp/socks5-ws-proxy-nginx.pid;
error_log /tmp/socks5-ws-proxy-nginx-error.log;

events {
    worker_connections 64;
}

http {
    access_log /tmp/socks5-ws-proxy-nginx-access.log;

    server {
        listen 127.0.0.1:40443 ssl;
        server_name localhost;

        ssl_certificate     ../certs/cert.pem;
        ssl_certificate_key ../certs/key.pem;

        location /ws-proxy {
            proxy_pass http://127.0.0.1:44088;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}
